# Generated by Django 3.2.3 on 2021-05-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
    ]
