# Generated by Django 3.2.3 on 2021-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20210528_1254'),
        ('products', '0003_auto_20210528_1254'),
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart_products',
            field=models.ManyToManyField(related_name='cart', through='purchases.Cart', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bought_products',
            field=models.ManyToManyField(related_name='bought', through='purchases.Purchase', to='products.Product'),
        ),
    ]
