# Generated by Django 3.2.3 on 2021-05-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210525_2032'),
        ('purchases', '0001_initial'),
        ('products', '0002_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bought_products',
            field=models.ManyToManyField(through='purchases.Purchase', to='products.Product'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
