# Generated by Django 3.2.1 on 2021-05-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210518_1506'),
        ('profiles', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bought_products',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='money_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
