# Generated by Django 3.2.3 on 2021-05-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210518_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=40, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
