# Generated by Django 3.2.3 on 2021-05-29 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20210528_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='purchases.payment'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='purchases.shipping'),
        ),
    ]
