# Generated by Django 3.2.3 on 2021-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('amount', models.IntegerField(default=1)),
                ('product_model', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=50)),
                ('buy_now', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auction_starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('publicly_listed', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
