# Generated by Django 3.2.1 on 2021-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('buy_now', models.DecimalField(decimal_places=2, max_digits=8)),
                ('auction_starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
            ],
        ),
    ]
