# Generated by Django 3.2.3 on 2021-05-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='buy_now',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='auction_starting_price',
        ),
    ]
