# Generated by Django 3.2.3 on 2021-06-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_stars'),
        ('products', '0004_product_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Books', 'Books'), ('Arts', 'Arts'), ('Fashion', 'Fashion'), ('Services', 'Services'), ('Home', 'Home'), ('Industrial', 'Industrial'), ('Health', 'Health'), ('Kids', 'Kids'), ('Garden', 'Garden'), ('Sport', 'Sport'), ('Motorization', 'Motorization'), ('Immovables', 'Immovables')], default='Books', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comments.Comment'),
        ),
    ]
