# Generated by Django 3.2.3 on 2021-05-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210525_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='auction_starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_now',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
