# Generated by Django 3.2.3 on 2021-05-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210525_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='seller',
        ),
        migrations.AlterField(
            model_name='product',
            name='customers_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'Nothing special'), (4, 'Good'), (5, 'Very good')], default=None, null=True),
        ),
    ]
