# Generated by Django 3.2.3 on 2021-05-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210525_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customers_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customers_review',
        ),
        migrations.AlterField(
            model_name='product',
            name='publicly_listed',
            field=models.BooleanField(default=True),
        ),
    ]
